config/routes.rb
Dgd::Application.routes.draw do
  
  resources :downloads do
    member do
      get 'view_all'
    end
  end
  resources :users do
    member do
      get 'change_password'
      put 'change_password'
      get 'edit_profile'
      put 'edit_profile'  
        end
    
    resources :downloads do
    member do
      get 'view_all'
    end
  end
   resources :faqs do
    member do
      get 'view_all'
    end
    end
  resources :news do
    member do
      get 'view_all'
      get 'press_release'
      get 'edit_press_release'
    end
  end
 resources :events do
     member do
       get 'view_all'
     end
   end
   resources :videos do
      
   end
   resources :newspubs do
     
   end
   resources :photos do
      
   end
  end
  
  resources :events do
     member do
       get 'view_all'
     end
   end
  resources :photos do
     member do
       get 'view_all'
     end
   end
  resources :videos do
     member do 
    get 'view_all'
    end
  end 
  resources :newspubs do
     member do
       get 'view_all'
     end
   end
  
  
    resources :faqs do
    member do
      get 'view_all'
    end
  end
  resources :news do
    member do
      get 'view_all'
      get 'press_release'
      get 'edit_press_release'
    end
  end
  match "/signup" => "users#new"  
  
 
  resources :sessions , :only=>[:create, :new,:destroy]
  get "sessions/destroy"
  match "/login" => "sessions#new"
  match "/admin" => "sessions#new"
  match "/admin" => "sessions#new"
  match "/logout" => "sessions#destroy"
  
  root to:"public#index"
  
  resources :public, :only=>[:index, :about,:contact,:partners,:sitemap]
  match "public" =>'public#index'
  match "public/" =>'public#index'  
  match "/about" => "public#about"
  match "/contact" => "public#contact"
  match "/partners" => "public#partners"
  match "/disclaimer" => "public#disclaimer"
  match "/sitemap" => "public#sitemap"
  
  resources :dashboard, :only=>[:index] ,:via => 'get'
  match "/myhome" =>'dashboard#index'
  
  match '/feed' => 'newspubs#feed' ,
     :as => :feed, :defaults => { :format => 'rss' }

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  
  before_filter :login_required, :only => ['index']
  def index
    
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div class="row-fluid">
<div class="sbh effect8">
<div class="well effect7">
<div class="sbh"><h2>System Dashboard</h2></div>
<div class="row-fluid">
<div class="span4 breadcrumb">
<div class="sbh effec7"><i class="icon-user"></i> User Manager</div>
<a href="<%= signup_path %>" class="btn"><i class="icon-plus-sign"></i> Add User</a>
<a href="<%= users_path %>" class="btn"><i class="icon-list-alt"></i> Manage</a>
</div>
<!--
<div class="span4 breadcrumb">
<div class="sbh effect7"><i class="icon-globe"></i> Partners Manager </div>
<a href="#" class="btn"><i class="icon-plus-sign"></i> Add Partners</a>
<a href="#" class="btn"><i class="icon-list-alt"></i> Manage</a>
</div>
-->
<div class="span4 breadcrumb">
<div class="sbh effect7"><i class="icon-book"></i> Newsletters and Publications Manager </div>  
<a href="<%= new_user_newspub_path current_user %>" class="btn"><i class="icon-plus-sign"></i> Add</a>
<a href="<%= newspubs_path %>" class="btn"><i class="icon-list-alt"></i> Manage</a>
</div>


<div class="span4 breadcrumb">
<div class="sbh effect7"><i class="icon-facetime-video"></i> Downloads Manager </div>
<a href="<%= new_user_download_path current_user %>" class="btn"><i class="icon-plus-sign"></i> Add</a>
<a href="<%= downloads_path %>" class="btn"><i class="icon-list-alt"></i> Manage</a>
</div>
</div>
<div class="row-fluid">
<div class="span4 breadcrumb">
<div class="sbh effect7"><i class="icon-calendar"></i> Events Manager </div>
<a href="<%= new_user_event_path current_user %>" class="btn"><i class="icon-plus-sign"></i> Add</a>
<a href="<%= events_path %>" class="btn"><i class="icon-list-alt"></i> Manage</a>
</div>
<div class="span4 breadcrumb">
<div class="sbh effect7"><i class="icon-headphones"></i> News Manager </div>
<a href="<%= new_user_news_path current_user%>" class="btn"><i class="icon-plus-sign"></i> Add News</a>
<a href="<%= news_index_path %>" class="btn"><i class="icon-list-alt"></i> Manage</a>
</div>
 
 
<div class="span4 breadcrumb">
<div class="sbh effect7"><i class="icon-picture"></i> Photo Gallery Manager </div>
<a href="<%= new_user_photo_path current_user%>" class="btn"><i class="icon-plus-sign"></i> Add Photo's</a>
<a href="<%= photos_path %>" class="btn"><i class="icon-list-alt"></i> Manage</a>
</div>
</div>
</div>
<div class="row-fluid">
	<div class="span4 breadcrumb">
<div class="sbh effect7"><i class="icon-th-list"></i> Videos Manager </div>
<a href="<%= new_user_video_path current_user %>" class="btn"><i class="icon-plus-sign"></i> Add Video</a>
<a href="<%= videos_path %>" class="btn"><i class="icon-list-alt"></i> Manage</a>
</div>
<div class="span4 breadcrumb">
<div class="sbh effect7"><i class="icon-th-list"></i> FAQ Manager </div>
<a href="<%= new_user_faq_path current_user %>" class="btn"><i class="icon-plus-sign"></i> Add FAQ</a>
<a href="<%= faqs_path %>" class="btn"><i class="icon-list-alt"></i> Manage</a>
</div>
<div class="span4 breadcrumb">
<div class="sbh effect7"><i class="icon-comment"></i> Feedback Manager </div>
<a href="#" class="btn"><i class="icon-list-alt"></i> Manage</a>
</div>
</div>
</div>