config/routes.rb
Dgd::Application.routes.draw do
  
  resources :downloads do
    member do
      get 'view_all'
    end
  end
  resources :users do
    member do
      get 'change_password'
      put 'change_password'
      get 'edit_profile'
      put 'edit_profile'  
        end
    
    resources :downloads do
    member do
      get 'view_all'
    end
  end
   resources :faqs do
    member do
      get 'view_all'
    end
    end
  resources :news do
    member do
      get 'view_all'
      get 'press_release'
      get 'edit_press_release'
    end
  end
 resources :events do
     member do
       get 'view_all'
     end
   end
   resources :videos do
      
   end
   resources :newspubs do
     
   end
   resources :photos do
      
   end
  end
  
  resources :events do
     member do
       get 'view_all'
     end
   end
  resources :photos do
     member do
       get 'view_all'
     end
   end
  resources :videos do
     member do 
    get 'view_all'
    end
  end 
  resources :newspubs do
     member do
       get 'view_all'
     end
   end
  
  
    resources :faqs do
    member do
      get 'view_all'
    end
  end
  resources :news do
    member do
      get 'view_all'
      get 'press_release'
      get 'edit_press_release'
    end
  end
  match "/signup" => "users#new"  
  
 
  resources :sessions , :only=>[:create, :new,:destroy]
  get "sessions/destroy"
  match "/login" => "sessions#new"
  match "/admin" => "sessions#new"
  match "/admin" => "sessions#new"
  match "/logout" => "sessions#destroy"
  
  root to:"public#index"
  
  resources :public, :only=>[:index, :about,:contact,:partners,:sitemap]
  match "public" =>'public#index'
  match "public/" =>'public#index'  
  match "/about" => "public#about"
  match "/contact" => "public#contact"
  match "/partners" => "public#partners"
  match "/disclaimer" => "public#disclaimer"
  match "/sitemap" => "public#sitemap"
  
  resources :dashboard, :only=>[:index] ,:via => 'get'
  match "/myhome" =>'dashboard#index'
  
  match '/feed' => 'newspubs#feed' ,
     :as => :feed, :defaults => { :format => 'rss' }

end

app/views/shared/_footer_hidden.html.haml
<div id="acticity" class="modal hide fade">
<div class="modal-header">
<button class="close" data-dismiss="modal">&times;</button>
<h3>Welcome to DGD</h3>
</div>
<div class="modal-body">
The Democratic Governance for Development (DGD) project is an electoral cycle (2010-2015) project designed to provide a coordinated mechanism for supporting the deepening of democracy in Nigeria by international donors and partners. 
<p>
The main objective of the project is to assist Nigerian authorities to consolidate and advance democratic governance and accountability in order to achieve the stated development priorities and outcomes of the country. Managed by the UNDP, the project is jointly financed by the European Union, the UK Department for International Cooperation, the Canadian International Development Agency, the Korea International Cooperation Agency and UNDP. 
</p>
<p>
Of all actors involved in supporting the electoral process in Nigeria, DGD has provided the most comprehensive assistance under its 6 main areas of intervention aimed at strengthening the National Assembly, Political Parties, improving the electoral process, increasing the capacity and performance of Civil Society, reinforcing the role and effectiveness of the mass media and empowering women in political governance with DGD experts providing technical insights and guidance.
</p>
<p>
The first phase of the project (April 2010-May 2011) focused primarily on support for voter registration, civic education, media training, women's political representation, training for elections tribunal staff and election observers, and production of information materials and electoral kits aimed at making the 2011 general elections free, fair and credible. The project is currently in a project reformulation process in order to recalibrate the efficacy of its support to Nigeria's democracy and ensure that it follows the Electoral Cycle Approach which in addition to electoral support focuses on deepening democracy and developing the capacities of key democratic Institutions.
</p>
</div>
<div class="modal-footer">
<a href="#" class="btn" data-dismiss="modal" >Close</a>
</div>
</div>

app/views/shared/_fotts.html.haml
-#<div class="sbhb fbn effect7" align="center">
-#<a href = "
-#= about_path 
-#"> About DGD</a> &bull; 
-#<a href="
-#= view_all_news_path 0
-#">DGD News</a> &bull; 
-#<a href="
-#= contact_path
-#">Contact Us</a> &bull;
-#<a href="
-#">Disclaimer</a> &bull;  
-#<a href="
-#= sitemap_path
-#">Site Map</a>
-#</div>
-#<footer class="footer sbhbb effect7  fbn">
-#The Democratic Governance for Development &copy; 2012  
-#</footer>
<div class="footer sbhbb fbn effect7" align="center">
<a href="#{about_path}">About DGD</a> &bull; 
<a href="#{view_all_news_path(0)}">DGD News</a> &bull; 
<a href="#{contact_path}">Contact Us</a> &bull; 
<a href="#{sitemap_path}">Site Map</a>
<hr class="dark">
The Democratic Governance for Development &copy; 2012
</div>

app/views/shared/_headings.html.erb
<% if !signed_in? %>
<!--<div class="row-fluid">
<div class="span10">
<a href="./">
<%= image_tag("undp.png", :style=>"float:left;padding:7px 7px 7px 0; margin:0px 5px  0 -35px;") %>
</a></div>-->
<div class="row-fluid">
<div class="span10">
<div style="margin-left:240px;">
	<a href="./">
	
		<%= image_tag("undp_left.png", :width=>644,:height=>145) %>
			 </a>
	</div>
 
 
 </div>
     <div class="span5" style="text-align:right;">    
     <!--<a href="feedback.php" class="btn"><i class="icon-share-alt"></i> Feedback</a>
      <a href="download.php" class="btn btn-inverse"><i class="icon-white icon-download"></i> Downloads</a>
     <a href="contactus.php" class="btn btn-info"><i class="icon-white icon-bell"></i> Contact Us</a>
     <a href="sitemap.php" class="btn btn-primary"><i class="icon-white icon-map-marker"></i> Site Map</a>-->
     </div>
    </div>
   
  <div class="breadcrumb" style="padding-bottom:0px;">
       
      	<%= form_tag({:controller=>'newspubs',:action=>'view_all',:id=>0},:method=>'get',:class=>"tagx form-search") %>
      <input type="text" class="input span3 search-query" name="q" placeholder="Search Keyword"> 
      <select class="span2" style"margin-top:6px;" name="t"> 
      <option value="all">Both</option>
        <option value="newsletter">Newsletter</option>
        <option value="publications">Publications</option>
      </select>
      <button type="submit" class="btn"  style"margin-top:6px;"><i class="icon-search"></i> Search</button>

 <div class="pull-right">
        	<a href="<%= view_all_newspub_path 0  %>" class="btn btn-inverse"> Newsletters and Publications </a> 
        	<a href="<%= partners_path %>" class="btn btn-info">International Partners </a></div>
<div class="nosrednahabo">&nbsp;</div></form>
</div>
  

   
    <!--<div class="slyc effect8" style="padding-bottom:012px;">
      	<form class="tagx form-search">
      <input type="text" class="input span3 search-query" placeholder="Search Keyword"> 
      <select class="span2"> 
      	<option value="">Search as;</option>

        <option value="">Newsletter</option>
        <option value="Watches">Activities</option>
      </select>
      <button type="submit" class="btn"><i class="icon-search"></i> Search</button>

        <div class="pull-right">
        	<a href="<%= view_all_newspub_path 0 %>" class="btn btn-inverse"> Newsletters and Publications </a> 
        	<a href="<%= partners_path %>" class="btn btn-info">International Partners </a></div>
</form>
<div class="nosrednahabo">&nbsp;</div>
</div>-->

<% else %>

<div class="row-fluid">
<div class="span10">
<a href="./">
<%= image_tag("undp.png", :style=>"float:left;padding:7px; margin:0px 5px;") %>
</a></div>
    
     <div class="span5" style="text-align:right;">    
     <!--<a href="feedback.php" class="btn"><i class="icon-share-alt"></i> Feedback</a>
      <a href="download.php" class="btn btn-inverse"><i class="icon-white icon-download"></i> Downloads</a>
     <a href="contactus.php" class="btn btn-info"><i class="icon-white icon-bell"></i> Contact Us</a>
     <a href="sitemap.php" class="btn btn-primary"><i class="icon-white icon-map-marker"></i> Site Map</a>-->
     </div>
    </div>
   
   
   
    <div class="breadcrumb" style="padding-bottom:0px;">
      		<%= form_tag({:controller=>'newspubs',:action=>'view_all',:id=>0},:method=>'get',:class=>"tagx form-search") %>
      <input type="text" class="input span3 search-query" name="q" placeholder="Search Keyword"> 
      <select class="span2" style"margin-top:6px;" name="t"> 
      <option value="all">Both</option>
        <option value="newsletter">Newsletter</option>
        <option value="publications">Publications</option>
      </select>
      <button type="submit" class="btn"><i class="icon-search"></i> Search</button>

        <div class="pull-right">
        	 
        	</div>
</form>
<div class="nosrednahabo">&nbsp;</div>
</div>
<% end %>

app/views/shared/_logged_in.html.erb
 <div class="row-fluid">
  <div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
  <div class="container">
  <a  href="<%= myhome_path%> class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  </a>
  <a class="brand" href="<%= myhome_path%>"> Hello, <%= current_user.firstname %> <%= current_user.lastname %></a>
  <div class="nav-collapse collapse">
  <ul class="nav">
  <li class="">
  <a    href="<%= myhome_path %>"><i class="icon-white icon-home"></i></a>
  </li>
  <li class="divider-vertical"></li>
  <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.username %> Profile<b class="caret"></b></a>
  <ul class="dropdown-menu">
  <li><a href="<%= user_path current_user %>">View Profile</a></li>
  <li><a href="<%= edit_profile_user_path current_user %>">Edit Profile</a></li>
  <li><a href="<%= change_password_user_path current_user.id %>">Change Password</a></li>
  
  </ul>
  </li>
   
  <li class="divider-vertical"></li>
  <li class="">
  <a href="#"></a>&nbsp;
  </li>
  <li class="divider-vertical"></li>
    
  <li class="">
  <a href="<%= logout_path%>">Logout</a>
  </li> 
  </ul> </div>
  </div>
  </div>
  </div>
  </div>

app/views/shared/_paginate.html.erb
<div class="apple_pagination">
    <div class="page_info">
      <%= page_entries_info @users %>
    </div>
    <%= will_paginate nil, :container => false %>
  </div>

app/views/shared/_partners_smedia.html.haml
<div class="sbh effect7">
Follow Us On
<hr />
=image_tag "Facebook.png"
=image_tag "Twitter.png" 
=image_tag "Google_Talk.png"
=image_tag "Youtube.png" 
</div>

app/views/shared/_topnav.html.erb
<%  if !signed_in? %>
<div class="row-fluid">
  <div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
  <div class="container">
  <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  </a>
  <div class="nav-collapse collapse">
  <ul class="nav">
  <li class="">
  <a href="<%= root_path%>"><i class="icon-white icon-home"></i></a>
  </li>
  <li class="divider-vertical"></li>
  <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">About<b class="caret"></b></a>
  <ul class="dropdown-menu">
  <li><a href="<%= about_path %>">About DGD</a></li>
  <li><a href="http://www.ng.undp.org" target="_blank">About UNDP</a></li>
  </ul>
  </li>
  <li class="divider-vertical"></li>
  <li class="">
  <a href="<%= view_all_event_path 0%>"> Events Calendar  </a>
  </li>
  <li class="divider-vertical"></li>
  <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Activities<b class="caret"></b></a>
  <ul class="dropdown-menu">
  <li><a href="#">Activity Discussions</a></li>
  </ul>
  </li>
  <li class="divider-vertical"></li>
  <li class="">
  <a href="<%= view_all_news_path 0%>">DGD News</a>
  </li>
  <li class="divider-vertical"></li>
  <li class="">
  <a href="<%= view_all_faq_path 0%>">FAQ</a>
  </li>
  <li class="divider-vertical"></li>
  <li class="">
  <a href="<%= view_all_photo_path  0%>">Photos</a>
  </li>
  <li class="divider-vertical"></li>
  <li class="">
  <a href="<%= view_all_download_path  0 %>">Downloads</a>
  </li>
  <li class="divider-vertical"></li>
  <li class="">
  <a href="#">Feedback</a>
  </li>
  </ul> </div>
  </div>
  </div>
  </div></div>
<% else %>
<%= render "shared/logged_in" %> 
<% end %>

app/views/shared/_tweets.html.erb
<% if @tweeter %>
<ul class= "list">
<% @tweeter.each do |t| %>
<li style="font-size:12px; clear:both; padding:0; margin: 0">
<b> @<%= "#{t.user.screen_name}"%> </b>: 
 <%= "#{t.text}".html_safe %> 	
</li>
<%end; end %>
</ul>

app/views/shared/_videos.html.erb
<% unless @recent_videos.blank? %>
<%  @recent_videos.each do |rv| %>
<% if !Rails.env.development? && rv.location =='Youtube' %>
  <iframe width="331" height="216" src="<%= rv.url%>"  frameborder="0" allowfullscreen>
  </iframe>

  <% else %>
<img src="images/vidimg2.png">

  <% end %>
  <% end %>
<% end %>