config/routes.rb
Dgd::Application.routes.draw do
  
  resources :downloads do
    member do
      get 'view_all'
    end
  end
  resources :users do
    member do
      get 'change_password'
      put 'change_password'
      get 'edit_profile'
      put 'edit_profile'  
        end
    
    resources :downloads do
    member do
      get 'view_all'
    end
  end
   resources :faqs do
    member do
      get 'view_all'
    end
    end
  resources :news do
    member do
      get 'view_all'
      get 'press_release'
      get 'edit_press_release'
    end
  end
 resources :events do
     member do
       get 'view_all'
     end
   end
   resources :videos do
      
   end
   resources :newspubs do
     
   end
   resources :photos do
      
   end
  end
  
  resources :events do
     member do
       get 'view_all'
     end
   end
  resources :photos do
     member do
       get 'view_all'
     end
   end
  resources :videos do
     member do 
    get 'view_all'
    end
  end 
  resources :newspubs do
     member do
       get 'view_all'
     end
   end
  
  
    resources :faqs do
    member do
      get 'view_all'
    end
  end
  resources :news do
    member do
      get 'view_all'
      get 'press_release'
      get 'edit_press_release'
    end
  end
  match "/signup" => "users#new"  
  
 
  resources :sessions , :only=>[:create, :new,:destroy]
  get "sessions/destroy"
  match "/login" => "sessions#new"
  match "/admin" => "sessions#new"
  match "/admin" => "sessions#new"
  match "/logout" => "sessions#destroy"
  
  root to:"public#index"
  
  resources :public, :only=>[:index, :about,:contact,:partners,:sitemap]
  match "public" =>'public#index'
  match "public/" =>'public#index'  
  match "/about" => "public#about"
  match "/contact" => "public#contact"
  match "/partners" => "public#partners"
  match "/disclaimer" => "public#disclaimer"
  match "/sitemap" => "public#sitemap"
  
  resources :dashboard, :only=>[:index] ,:via => 'get'
  match "/myhome" =>'dashboard#index'
  
  match '/feed' => 'newspubs#feed' ,
     :as => :feed, :defaults => { :format => 'rss' }

end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id                :integer          not null, primary key
#  user_id           :integer
#  title             :string(255)
#  description       :text
#  synopsis          :text
#  start_date        :datetime
#  end_date          :datetime
#  created_at        :datetime
#  updated_at        :datetime
#  file_file_name    :string(255)
#  file_content_type :string(255)
#  file_file_size    :integer
#  file_updated_at   :datetime
#

class Event < ActiveRecord::Base
  
   belongs_to :user , :foreign_key=>:user_id
   attr_accessible :title ,:start_date,:end_date , :description , :file,:synopsis ,:user_id
  
   has_attached_file :file  , :styles => { :medium => "300x300>", :thumb => "100x100>" }
  
   has_event_calendar :start_at_field  => 'start_date', :end_at_field => 'end_date'
  
  validates :file, :attachment_presence => true
  validates_with AttachmentPresenceValidator, :attributes => :file

  validates  :title,  :presence => true,
                      :length => {:maximum => 255},
                      :uniqueness => {:case_sensitive=>false}
  
  validates  :start_date,  :presence => true
                        
 validates  :end_date,  :presence => true
                        
  
 
  validates  :description, :presence => true, 
                           :length=>{:minimum=>1}  #,:allow_blank=>true
  

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  
  before_filter :login_required, :only=>['new','destroy','edit','index','update','create']
  before_filter :check_user_group , :only=>['edit','new'] 
  def new
    
    @event = @model= current_user.events.build(params[:event])
  end

  def index
    if request.get? && params[:user_id]
      @title = "My Events"
    @events = Event.where(:user_id=>params[:user_id]).paginate(:page=>params[:page],:per_page=>20)
   
    else
      @title = "All Events"
      @events = Event.paginate(:page=>params[:page],:per_page=>1)
    
    
    end
  end

  def view_all
    @title = "All Events"    
    @events = Event.paginate(:page=>params[:page],:per_page=>10)
    
    
    
  end

  
  def edit
    @event = @model = Event.find_by_id(params[:id])
  end
  

  def update
    
     if request.put?
      
     @newspub = @model= Event.find(:first,:conditions=>{:user_id =>current_user.id,:id =>params[:id]})
     if @newspub.nil?
       flash[:error] =" Invalid Selection detected. "
       redirect_to user_events_path current_user
       return nil
     end
       #find(:first,:conditions=>{"user_id"=>current_user.id,"id"=>params[:newspub][:id]})
      
      if (params[:event][:file])
              
       @newspub.file=nil
       @newspub.save
       
      end      
        
       params[:event][:user_id] = current_user.id
       # @newspub = @model= Newspub.find(:first,:conditions=>{:user_id =>current_user.id,:id =>params[:newspub][:id]})
      
       if @newspub.update_attributes(params[:event])
       flash[:notice] = "Successfully Updated the Event: #{params[:event][:title]}"
       
       elsif !params[:event][:file]
        
         params[:event][:user_id] = current_user.id
         # @newspub = @model= Newspub.find(:first,:conditions=>{:user_id =>current_user.id,:id =>params[:newspub][:id]})
         @newspub.update_attributes(params[:event])
         flash[:notice] = "Successfully Updated the Event  #{params[:event][:title]}"        
       else
         flash[:error] = "Failed to update the Event"  
      end
      
      redirect_to user_events_path current_user.id 
      end
  end

  def create
    if request.post?
      @newspub = @model = current_user.events.build(params[:event])
      if @newspub.save 
     flash[:notice]= "successfully saved a new  Event titled #{params[:event][:title]}"
     
      redirect_to user_events_path current_user.id
        
      else
     flash[:error]= "Some errors occured. We were unable to save uploaded file! Blank or Duplicates  files are not acceptable"
     # session[:new_model]= current_user.newspubs.build(params[:newspub]).errors
      #render :new
      render :new
      end
    end
  end

  def destroy
    
    @newspub=Event.find_by_id(params[:id])
       if(@newspub && @newspub.user_id = current_user.id)
       @newspub.file = nil
       @newspub.save
       @newspub.destroy
       flash[:notice] = "Successfully deleted the Event:  #{params[:event][:title]} "
       redirect_to nevents_path  
     else
       flash[:error] = "Unable to delete the Event:  #{params[:event][:title]}"
        redirect_to events_path
     end
  end

  def show
      @event = @model = Event.find_by_id(params[:id])
  end

end

app/helpers/events_helper.rb
module EventsHelper
  
  
end

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<div class="nosrednahabo">&nbsp;</div>
<%= session[:new_model] = @new_model %>
<%= render :partial => "shared/errors/error_messages" ,:lnew_model=>@new_model %>
<div class="row-fluid">
<div class="sbh effect8">
<div class="breadcrumb"><a href="<%= myhome_path %>">System Dashboard</a>
<i class="icon-chevron-left"></i> <a href="<%= user_events_path current_user %>">View My Events</a> <i class="icon-chevron-left"></i> </div>
<div class="well effect7">
<div class="sbh"><h2>System Dashboard &raquo; Event  Add</h2></div>
<div class="sbh bgff">
<div class="row-fluid">

<%= form_for(@event, :html => { :multipart => true }) do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.label "Logo" %>
   <%= form.file_field :file %>
   <%= form.label :start_date %>
  <!-- #form.date_select :start_date,:start_year=>2012,:end_year=>2015 ,:use_short_month=>true,:order=>[:day,:month,:year]%>
  -->
  <%=  form.text_field :start_date ,:class=>'datepicker'%>
  <%= form.label :end_date %>
  <%=  form.text_field :end_date ,:class=>'datepicker'%>
 
   <!-- #form.date_select :end_date ,:start_year=>2012,:end_year=>2015,:use_short_month=>true,:order=>[:day,:month,:year], :html=>{:class=>'input-small'} %>
  
  -->
  <%= form.label "Event Brief" %>
  <%= form.text_area :synopsis,:size=>"10x5"  %>
  <%= form.label "description" %>
  <%= form.text_area :description,:size=>"10x5" ,:class=>'tinymce' %>
  <br/>
  <button class="btn btn-primary"><i class="icon-white icon-plus-sign"></i> Save</button>
<% end %>


    
</div>  
</div>
</div>
</div>  

app/views/events/index.html.erb
<div class="sbh effect8">
        	<div class="breadcrumb"><a href="<%= myhome_path %>">System Dashboard</a> <i class="icon-chevron-left"></i> 
        		  <a href="<%= events_path %>">View All Events</a>  </div>
          <div class="well effect7">
           	<div class="sbh"><h2>System Dashboard &raquo; <%= @title %></h2></div>
			<div class="sbh bgff">

		<table class="table table-bordered table-striped">
        <thead>
        	<caption>Total Uploads &raquo; <%= @events.count.to_s %></caption>
           <thead class="table"><tr>
           
            <th> Event</th>
            <th> Event Logo </th>
            <th> Event Start date</th>
            <th> Event End date</th>
             <th>Action</th>
          </tr></thead>
        </thead>
        <tbody>
        	<% @events.each do |newspub|%>
          <tr>
            
            
                       <td><%=  newspub.title %></td>
                       <td><%=  image_tag newspub.file.url(:thumb) %></td>
                        <td><%=  time_tag newspub.start_date %>. </td>
                        
                       <td><%=  time_tag newspub.end_date%>. </td>
            <td>
            	<a class="btn"  data-toggle="modal" href="#<%= newspub.id.to_s%>"><i class="icon-list-alt"></i></a>
                <a class="btn" href="<%= edit_user_event_path(newspub.user_id,newspub.id) %>"><i class="icon-pencil"></i></a>
             
               <%= link_to "<i class=\"icon-trash\"></i>".html_safe, newspub ,:method => :delete,:class=>"btn" ,"date-remote"=>true,:confirm=>"Delete #{newspub.title} ?",:title => "Delete #{newspub.title}"%>
                
            </td>
          </tr>
           
           <% end %>
          
        </tbody>
      </table>
       <%= render "shared/paginate"%>
            </div>
            
          </div>
         
        </div>
        <% @events.each do |user| %>
 	     <div id="<%= user.id.to_s %>" class="modal hide fade">
            <div class="modal-header">
              <button class="close" data-dismiss="modal">&times;</button>
              <h3><%= user.title %></h3>
            </div>
            <div class="modal-body">
				<div class="well effect8">                	
                    <ul class="tabs-stacked">
                    	<li class="lino">File &raquo; <%= user.title %> </li>
                                 <li class="lino">Created By &raquo; <%= user.user.username.capitalize %>   </li>
                    <li class="lino">Created &raquo; <%= distance_of_time_in_words_to_now(user.created_at,false).to_s %>  ago. </li>
             
                    </ul>
            	</div>
            </div>

            <div class="modal-footer">
              <a href="#" class="btn" data-dismiss="modal" >Close</a>
            </div>
          </div>
          <% end %>
          <div id="udel" class="modal hide fade">
            <div class="modal-header">
              <h3>Delete User?</h3>
            </div>
            <div class="modal-body">
				<div class="alert alert-danger">                	
                    Are you sure you want to delete user <em>'Name in full'</em>?
                    <a href="" class="btn-danger btn"><i class="icon-white icon-ok"></i> Yes</a>
            	</div>
            </div>

            <div class="modal-footer">
              <a href="#" class="btn" data-dismiss="modal"><i class="icon-remove"></i> Cancel</a>
            </div>
 
   

app/views/events/new.html.erb
<div class="nosrednahabo">&nbsp;</div>
<%= session[:new_model] = @new_model %>
<%= render :partial => "shared/errors/error_messages" ,:lnew_model=>@new_model %>
<div class="row-fluid">
<div class="sbh effect8">
<div class="breadcrumb"><a href="<%= myhome_path %>">System Dashboard</a>
<i class="icon-chevron-left"></i> <a href="<%= user_events_path current_user %>">View My Events</a> <i class="icon-chevron-left"></i> </div>
<div class="well effect7">
<div class="sbh"><h2>System Dashboard &raquo; Event  Add</h2></div>
<div class="sbh bgff">
<div class="row-fluid">

<%= form_for current_user.events.build(:user=>current_user), :html => { :multipart => true } do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.label "Logo" %>
   <%= form.file_field :file %>
   <%= form.label :start_date %>
  <!-- #form.date_select :start_date,:start_year=>2012,:end_year=>2015 ,:use_short_month=>true,:order=>[:day,:month,:year]%>
  -->
  <%=  form.text_field :start_date ,:class=>'datepicker'%>
  <%= form.label :end_date %>
  <%=  form.text_field :end_date ,:class=>'datepicker'%>
 
   <!-- #form.date_select :end_date ,:start_year=>2012,:end_year=>2015,:use_short_month=>true,:order=>[:day,:month,:year], :html=>{:class=>'input-small'} %>
  
  -->
  <%= form.label "Event Brief" %>
  <%= form.text_area :synopsis,:size=>"10x5"  %>
  <%= form.label "description" %>
  <%= form.text_area :description,:size=>"10x5" ,:class=>'tinymce' %>
  <br/>
  <button class="btn btn-primary"><i class="icon-white icon-plus-sign"></i> Save</button>
<% end %>


    
</div>  
</div>
</div>
</div>  

app/views/events/show.html.erb
 <div class="row-fluid">
    
   	  <div class="span9">
        <div class="sbh effect8">
       		<div class="sbhb effect7">
            <h2><%= @event.title%></h2>
            </div>
          	<ul id="myTab" class="nav nav-tabs">
            <li class="active"><a href="#partners" data-toggle="tab"><i class="icon-globe"></i> Details</a></li>
                   <li><a href="#" class="btn btn-success">Begins on : <%= time_tag @event.start_date %>.</a></li>
                   <li><a href="#" class="btn btn-danger">Ends on : <%= time_tag @event.end_date %>.</a></li>
          </ul>
          <div id="myTabContent" class="tab-content">
            <div class="tab-pane fade in active" id="partners">
				<div class="sbh fbn">
	                <%= @event.description.html_safe %>
                    
                </div>
            </div>
             
          </div>
          
          </div>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

app/views/events/view_all.html.erb
<div class="row-fluid">
   	  <div class="span12" >
        <div class="sbh effect7 fbn" style="margin-bottom:15px;">
        	<div class="sbhb"><h2>Events </h2></div>
          <ul id="myTab" class="nav nav-tabs">
            <li class="active"><a href="#events" data-toggle="tab"><i class="icon-tasks"></i> Events</a></li>
            <!--<li><a href="#calenderMain" data-toggle="tab"><i class="icon-calendar"></i> Calender</a></li>    -->        
          </ul>
          <div id="myTabContent" class="tab-content">
            <div class="tab-pane fade in active" id="events">
            	<% @events.each_slice(4) do |e| %>
                  <ul class="thumbnails">
                  	 <% unless e[0].nil? %>
                    <li class="span3">
                    <div class="thumbnail sbh fbn lh4">
                    <%= image_tag(e[0].file.url) unless e[0].nil?%>
                    <h5 class="m7"><%= e[0].title unless e[0].nil? %></h5>
                     <%= e[0].synopsis unless e[0].nil? %>
                    <a  href="<%= event_path e[0] unless e[0].nil? %>" class="btn btn-inverse"><i class="icon-white icon-info-sign"></i> Read More</a>
                    </div>
                    </li>
                     <% end %>
                    <% unless e[1].nil? %>
 					<li class="span3">
                    <div class="thumbnail sbh fbn lh4">
                     <%= image_tag(e[1].file.url) unless e[1].nil?%>
                    <h5 class="m7"><%= e[1].title unless e[1].nil? %></h5>
                     <%= e[1].synopsis unless e[1].nil? %>
                     <a  href="<%= event_path e[1] unless e[1].nil? %>" class="btn btn-inverse"><i class="icon-white icon-info-sign"></i> Read More</a>
                    </div>
                    </li>
                    <% end %>
                     <% unless e[2].nil? %>
                    <li class="span3">
                    <div class="thumbnail sbh fbn lh4">
                    <%= image_tag(e[2].file.url) unless e[2].nil?%>
                    <h5 class="m7"><%= e[2].title unless e[2].nil? %></h5>
                     <%= e[2].synopsis unless e[2].nil? %>
                    <a  href="<%= event_path e[2] unless e[2].nil? %>" class="btn btn-inverse"><i class="icon-white icon-info-sign"></i> Read More</a>
                    </div>
                    </li>
                     <% end %>
                      <% unless e[3].nil? %>
                    <li class="span3">
                    <div class="thumbnail sbh fbn lh4">
                    
                     <%= image_tag(e[3].file.url) unless e[3].nil?%>
                    <h5 class="m7"><%= e[3].title unless e[3].nil? %></h5>
                     <%= e[3].synopsis unless e[3].nil? %>
                    <a  href="<%= event_path e[3] unless e[3].nil? %>" class="btn btn-inverse"><i class="icon-white icon-info-sign"></i> Read More</a>
                     </div>
                    </li>
                     <% end %>
                 </ul>
                 <% end %>
   <%= render "shared/paginate"%>
            </div>
           <!-- <div class="tab-pane fade" id="calenderMain">
            	<div class="alert alert-info">
                	<button class="close" data-dismiss="alert">×</button>
                	<strong>Click</strong> the buttons to view calender events/activities.
                </div>
              
             	<div id='calendar1'>
             		 
             	</div>
           </div>-->
          </div>
          <hr>
       </div></div> 
        
      
  
       
     
 