config/routes.rb
Dgd::Application.routes.draw do
  
  resources :downloads do
    member do
      get 'view_all'
    end
  end
  resources :users do
    member do
      get 'change_password'
      put 'change_password'
      get 'edit_profile'
      put 'edit_profile'  
        end
    
    resources :downloads do
    member do
      get 'view_all'
    end
  end
   resources :faqs do
    member do
      get 'view_all'
    end
    end
  resources :news do
    member do
      get 'view_all'
      get 'press_release'
      get 'edit_press_release'
    end
  end
 resources :events do
     member do
       get 'view_all'
     end
   end
   resources :videos do
      
   end
   resources :newspubs do
     
   end
   resources :photos do
      
   end
  end
  
  resources :events do
     member do
       get 'view_all'
     end
   end
  resources :photos do
     member do
       get 'view_all'
     end
   end
  resources :videos do
     member do 
    get 'view_all'
    end
  end 
  resources :newspubs do
     member do
       get 'view_all'
     end
   end
  
  
    resources :faqs do
    member do
      get 'view_all'
    end
  end
  resources :news do
    member do
      get 'view_all'
      get 'press_release'
      get 'edit_press_release'
    end
  end
  match "/signup" => "users#new"  
  
 
  resources :sessions , :only=>[:create, :new,:destroy]
  get "sessions/destroy"
  match "/login" => "sessions#new"
  match "/admin" => "sessions#new"
  match "/admin" => "sessions#new"
  match "/logout" => "sessions#destroy"
  
  root to:"public#index"
  
  resources :public, :only=>[:index, :about,:contact,:partners,:sitemap]
  match "public" =>'public#index'
  match "public/" =>'public#index'  
  match "/about" => "public#about"
  match "/contact" => "public#contact"
  match "/partners" => "public#partners"
  match "/disclaimer" => "public#disclaimer"
  match "/sitemap" => "public#sitemap"
  
  resources :dashboard, :only=>[:index] ,:via => 'get'
  match "/myhome" =>'dashboard#index'
  
  match '/feed' => 'newspubs#feed' ,
     :as => :feed, :defaults => { :format => 'rss' }

end

app/models/news.rb
# == Schema Information
#
# Table name: news
#
#  id                      :integer          not null, primary key
#  caption                 :string(255)
#  news_content            :text
#  user_id                 :integer
#  author                  :string(255)
#  landing_page_image      :boolean
#  created_at              :datetime
#  updated_at              :datetime
#  release_file_name       :string(255)
#  release_content_type    :string(255)
#  release_file_size       :integer
#  release_updated_at      :datetime
#  news_image_file_name    :string(255)
#  news_image_content_type :string(255)
#  news_image_file_size    :integer
#  news_image_updated_at   :datetime
#  category                :string(255)
#

class News < ActiveRecord::Base
  belongs_to :user
  attr_accessible :release , :news_image, :category,:caption,:news_image ,:landing_page_image,:news_content , :author,:user_id
 
  has_attached_file :release  #, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  has_attached_file :news_image  , :styles => { :medium => "1000x1000>", :thumb => "100x100>" }
  
  validates :category , :presence =>true
 # validates :news_image, :attachment_presence => true
 #validates_with AttachmentPresenceValidator, :attributes => :news_image

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_filter :login_required , :only => ['new','index','create','update','edit','destroy']
  before_filter :check_user_group , :only => ['new','update','create','edit']
  def new
    @news=@model= current_user.news.build(params[:news])
  end

  def create
    
    if request.post?
      @news = @model = current_user.news.build(params[:news])
      if @news.save
        flash[:notice] = "You have successfully created a news item captioned:  #{params[:news][:caption]}"
       redirect_to user_news_index_path current_user 
       else
         flash[:errow] = "Errors occurred whilst saving"
         render new_news_path
      end
    end
  end

  def index
    if request.get? && !params[:user_id]
    @title = "All News"  
    
    @news=@model = News.paginate(:page=>params[:page],:per_page=>10)
    else
      @title = "My  Created News "  
    
    @news=@model = News.where(:user_id=>params[:user_id]).paginate(:page=>params[:page],:per_page=>10)
    end
  end

  def view_all
    @title = "All News"
    @news = News.paginate(:page=>params[:page],:per_page=>10)
    
  end

  def destroy
    
     @newspub= @model= News.find(params[:id])
       if(@newspub && (@newspub.user_id == current_user.id))
       @newspub.news_image = nil # To delete paperclip generated image
       @newspub.release = nil # To delete paperclip uploaded press_release
       
       @newspub.save
       @newspub.destroy
       flash[:notice] = "Successfully deleted the News Item:  #{@newspub.caption} "
       redirect_to news_index_path  
     elsif @newspub.nil?
       flash[:error] = "Unable to delete the News:  #{@newspub.caption} "
       redirect_to news_index_path 
     else
       flash[:error] = "Unable to delete the News:  #{@newspub.caption} "
        redirect_to news_path
     end
  end

  def edit 
    
    @news =@model= News.find(:first,:conditions=>{:user_id=>current_user.id,:id=>params[:id]})
    
    if params[:category] == 'press_release' 
     render :edit_press_release , :user_id => params[:user_id],:id => params[:id]
     
   
     
    end
  end

  def update
    if request.put?
       @news =@model= News.find(:first,:conditions=>{:user_id=>current_user.id,:id=>params[:id]})
      if params[:news][:news_image]
        @news.news_image= nil
        @news.save
         params[:news][:user_id] = current_user.id
       # @newspub = @model= Newspub.find(:first,:conditions=>{:user_id =>current_user.id,:id =>params[:newspub][:id]})
         @news.update_attributes(params[:news])
         flash[:notice] = "Successfully Updated the  #{params[:news][:category]}"
         redirect_to news_index_path
      elsif !params[:news][:news_image]
        
         params[:news][:user_id] = current_user.id
         # @newspub = @model= Newspub.find(:first,:conditions=>{:user_id =>current_user.id,:id =>params[:newspub][:id]})
          @news.update_attributes(params[:news])
         flash[:notice] = "Successfully Updated the  #{params[:news][:caption]}"   
         redirect_to news_index_path     
       else
         flash[:error] = "Failed to update the item"  
          render edit_news_path params[:id]
      end
    end
  end

  def show
    @news = @model = News.find_by_id(params[:id])
  end

def press_release
  @news = @model = current_user.news.build(params[:news])
end
  def edit_press_release
   @news =@model= News.find(:first,:conditions=>{:user_id=>current_user.id,:id=>params[:id]})
  end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/Copy of view_all.html.erb
 <div class="row-fluid">
   	  <div class="span12">
        <div class="sbh effect7 fbn" style="margin-bottom:15px;">
        	<div class="sbhb"><h2>News</h2></div>
          <ul id="myTab" class="nav nav-tabs">
            <li class="active"><a href="#latest" data-toggle="tab"><i class="icon-file"></i> Latest News</a></li>
            <li><a href="#past" data-toggle="tab"><i class="icon-briefcase"></i> Archive News</a></li>            
          </ul>
          <div id="myTabContent" class="tab-content">
            <div class="tab-pane fade in active" id="latest">
            	<ul class="thumbnails">
                    <li class="span3">
                    <div class="thumbnail sbh fbn lh4">
                    <img src="images/vt1.jpg"/>
                    <h5 class="m7">News 1 label</h5>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do 
                    eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                    <span class="label label-info">Date &raquo; August 8, 2012</span>
                    <hr>                    
                    <a data-toggle="modal" href="#popNews1" class="btn btn-inverse"><i class="icon-white icon-info-sign"></i> Read More</a>
                    </div>
                    </li>
 					<li class="span3">
                    <div class="thumbnail sbh fbn lh4">
                    <img src="images/vt2.jpg"/>
                    <h5 class="m7">News 2 label</h5>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do 
                    eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                    <span class="label label-info">Date &raquo; August 8, 2012</span>
                    <hr>
                    <a data-toggle="modal" href="#popNews2" class="btn btn-inverse"><i class="icon-white icon-info-sign"></i> Read More</a>
                    </div>
                    </li>
                    <li class="span3">
                    <div class="thumbnail sbh fbn lh4">
                    <img src="images/vt3.jpg"/>
                    <h5 class="m7">News 3 label</h5>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do 
                    eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                    <span class="label label-info">Date &raquo; August 3, 2012</span>
                    <hr>
                    <a data-toggle="modal" href="#popNews3" class="btn btn-inverse"><i class="icon-white icon-info-sign"></i> Read More</a>
                    </div>
                    </li>
                    <li class="span3">
                    <div class="thumbnail sbh fbn lh4">
                    <img src="images/vt4.jpg"/>
                    <h5 class="m7">News 4 label</h5>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do 
                    eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                    <span class="label label-info">Date &raquo; August 2, 2012</span>
                    <hr>
                    <a data-toggle="modal" href="#popNews4" class="btn btn-inverse"><i class="icon-white icon-info-sign"></i> Read More</a>
                    </div>
                    </li>
                 </ul>
                 
                  <%= render "shared/paginate"%>    
            </div>
          
                <div class="tab-pane fade" id="past">
				<ul class="thumbnails">
                    <li class="span3">
                    <div class="thumbnail sbh fbn lh4">
                    <img src="images/vt1.jpg"/>
                    <h5 class="m7">News 1 label</h5>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do 
                    eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                    <span class="label label-info">Date &raquo; August 8, 2012</span>
                    <hr>                    
                    <a data-toggle="modal" href="#popNews1" class="btn btn-inverse"><i class="icon-white icon-info-sign"></i> Read More</a>
                    </div>
                    </li>
 					<li class="span3">
                    <div class="thumbnail sbh fbn lh4">
                    <img src="images/vt2.jpg"/>
                    <h5 class="m7">News 2 label</h5>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do 
                    eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                    <span class="label label-info">Date &raquo; August 8, 2012</span>
                    <hr>
                    <a data-toggle="modal" href="#popNews2" class="btn btn-inverse"><i class="icon-white icon-info-sign"></i> Read More</a>
                    </div>
                    </li>
                    <li class="span3">
                    <div class="thumbnail sbh fbn lh4">
                    <img src="images/vt3.jpg"/>
                    <h5 class="m7">News 3 label</h5>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do 
                    eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                    <span class="label label-info">Date &raquo; August 3, 2012</span>
                    <hr>
                    <a data-toggle="modal" href="#popNews3" class="btn btn-inverse"><i class="icon-white icon-info-sign"></i> Read More</a>
                    </div>
                    </li>
                    <li class="span3">
                    <div class="thumbnail sbh fbn lh4">
                    <img src="images/vt4.jpg"/>
                    <h5 class="m7">News 4 label</h5>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do 
                    eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                    <span class="label label-info">Date &raquo; August 2, 2012</span>
                    <hr>
                    <a data-toggle="modal" href="#popNews4" class="btn btn-inverse"><i class="icon-white icon-info-sign"></i> Read More</a>
                    </div>
                    </li>
                    
                 </ul>
                <%= render "shared/paginate"%>               
            </div>
                <hr>
            </div>
            
          
        </div>

app/views/news/create.html.erb
<h1>News#create</h1>
<p>Find me in app/views/news/create.html.erb</p>

app/views/news/destroy.html.erb
<h1>News#destroy</h1>
<p>Find me in app/views/news/destroy.html.erb</p>

app/views/news/edit.html.erb
<div class="nosrednahabo">&nbsp;</div>
<%= session[:new_model] = @new_model %>
<%= render :partial => "shared/errors/error_messages" ,:lnew_model=>@new_model %>
<div class="row-fluid">
<div class="sbh effect8">
<div class="breadcrumb"><a href="<%= myhome_path %>">System Dashboard</a>
<i class="icon-chevron-left"></i> <a href="<%= user_events_path current_user %>">View My Events</a> <i class="icon-chevron-left"></i> </div>
<div class="well effect7">
<div class="sbh"><h2>System Dashboard &raquo; News Create</h2></div>
<div class="sbh bgff">
<div class="row-fluid">

<%= form_for @news, :html => { :multipart => true } do |form| %>
  <%= form.label :caption %>
  <%= form.text_field :caption %>
  <%= form.label :news_image %>
  <%= form.file_field :news_image %>
   <p class="alert alert-error">Include Image in Home Page :   <%= form.check_box :landing_page_image , :value=>1 %> </p>
   <%= form.label "News Content" %>
  <%= form.text_area :news_content,:size=>"10x5" ,:class=>'tinymce' %>
  <%= form.label "Author / Contributor" %>
  <!-- #form.date_select :start_date,:start_year=>2012,:end_year=>2015 ,:use_short_month=>true,:order=>[:day,:month,:year]%>
  -->
  <%=  form.text_field :author , :value => "#{current_user.firstname} #{current_user.lastname}" %>

  <%=  form.hidden_field :category ,:value => "news"%>
  <br/>
  <button class="btn btn-primary"><i class="icon-white icon-plus-sign"></i> Save</button>
<% end %>


    
</div>  
</div>
</div>
</div>  

app/views/news/edit_press_release.html.erb
<div class="nosrednahabo">&nbsp;</div>
<%= session[:new_model] = @new_model %>
<%= render :partial => "shared/errors/error_messages" ,:lnew_model=>@new_model %>
<div class="row-fluid">
<div class="sbh effect8">
<div class="breadcrumb"><a href="<%= myhome_path %>">System Dashboard</a>
<i class="icon-chevron-left"></i> <a href="<%= user_news_index_path current_user %>">View My News</a> <i class="icon-chevron-left"></i> </div>
<div class="well effect7">
<div class="sbh"><h2>System Dashboard &raquo; Press Release Add </h2></div>
<div class="sbh bgff">
<div class="row-fluid">

<%= form_for @news, :html => { :multipart => true } do |form| %>
  <%= form.label :caption %>
  <%= form.text_field :caption %>
     <%= form.hidden_field :landing_page_image, :value=>false %> 
   <%= form.label "File" %>
  <%= form.file_field :release %>
  
  <%=  form.hidden_field :category ,:value => "press_release"%>
  <br/>
  <button class="btn btn-primary"><i class="icon-white icon-plus-sign"></i> Save</button>
<% end %>


    
</div>  
</div>
</div>
</div>  

app/views/news/index.html.erb
<div class="sbh effect8">
        	<div class="breadcrumb"><a href="<%= myhome_path %>">System Dashboard</a> <i class="icon-chevron-left"></i> 
        		  <a href="<%= news_index_path  %>">View All News</a>  </div>
          <div class="well effect7">
           	<div class="sbh"><h2>System Dashboard &raquo; <%= @title %></h2></div>
			<div class="sbh bgff">

		<table class="table table-bordered table-striped">
        <thead>
        	<caption>Total Uploads &raquo; <%= @news.count.to_s %></caption>
           <thead class="table"><tr>
           
            <th> News Caption</th>
            <th> Image </th>
            <th> Type </th>
            <th> Author </th>
            
             <th>Action</th>
          </tr></thead>
        </thead>
        <tbody>
        	<% @news.each do |newspub|%>
          <tr>
            
            
                       <td><%=  newspub.caption %></td>
                       
                       <td><%=  image_tag newspub.news_image.url(:thumb) unless newspub.news_image.nil? %></td>
                     <% if newspub.release_file_name.nil? %>
                         <td><%=   newspub.category.gsub("_", "  ").capitalize   %> </td> 
                          <% else %>
                      <td><%=   link_to newspub.category.gsub("_", "  ").capitalize , newspub.release.url,:target=>"_blank"  %> </td> 
                       
                      <% end %>
                        <td><%=   newspub.author %> </td> 
                       
            <td>
            	<a class="btn"  data-toggle="modal" href="#<%= newspub.id.to_s%>"><i class="icon-list-alt"></i></a>
                <a class="btn" href="<%= edit_user_news_path(newspub.user_id,newspub.id, :category=>newspub.category) %>"><i class="icon-pencil"></i></a>
             
               <%= link_to "<i class=\"icon-trash\"></i>".html_safe, newspub ,:method => :delete,:class=>"btn" ,"date-remote"=>true,:confirm=>"Delete #{newspub.caption} ?",:title => "Delete #{newspub.caption}"%>
                
            </td>
          </tr>
           
           <% end %>
          
        </tbody>
      </table>
       <%= render "shared/paginate"%>
            </div>
            
          </div>
         
 
        <% @news.each do |user| %>
 	     <div id="<%= user.id.to_s %>" class="modal hide fade">
            <div class="modal-header">
              <button class="close" data-dismiss="modal">&times;</button>
              <h3><%= user.caption %></h3>
            </div>
            <div class="modal-body">
				<div class="well effect8">                	
                    <ul class="tabs-stacked">
                    	<li class="lino">File &raquo; <%= user.caption %> </li>
                                 <li class="lino">Created By &raquo; <%= user.user.username.capitalize %>   </li>
                    <li class="lino">Created &raquo; <%= distance_of_time_in_words_to_now(user.created_at,false).to_s %>  ago. </li>
             
                    </ul>
            	</div>
            </div>

            <div class="modal-footer">
              <a href="#" class="btn" data-dismiss="modal" >Close</a>
            </div>
          </div>
          <% end %>
          
           
           
 
   

app/views/news/new.html.erb
<div class="nosrednahabo">&nbsp;</div>
<%= session[:new_model] = @new_model %>
<%= render :partial => "shared/errors/error_messages" ,:lnew_model=>@new_model %>
<div class="row-fluid">
<div class="sbh effect8">
<div class="breadcrumb"><a href="<%= myhome_path %>">System Dashboard</a>
<i class="icon-chevron-left"></i> <a href="<%= user_news_index_path current_user %>">
	View My News</a> <i class="icon-chevron-left"></i> 
		 <a href="<%= press_release_user_news_path current_user.id ,0 %>"> New Press Release </a> <i class="icon-chevron-left"></i>
	</div>
<div class="well effect7">
<div class="sbh"><h2>System Dashboard &raquo; News Create</h2></div>
<div class="sbh bgff">
<div class="row-fluid">

<%= form_for current_user.news.build(:user=>current_user), :html => { :multipart => true } do |form| %>
  <%= form.label :caption %>
  <%= form.text_field :caption %>
  <%= form.label :news_image %>
  <%= form.file_field :news_image %>
   <p class="alert alert-error">Include Image in Home Page :   <%= form.check_box :landing_page_image ,:value =>1 %> </p>
   <%= form.label "News Content" %>
  <%= form.text_area :news_content,:size=>"10x5" ,:class=>'tinymce' %>
  <%= form.label "Author / Contributor" %>
  <!-- #form.date_select :start_date,:start_year=>2012,:end_year=>2015 ,:use_short_month=>true,:order=>[:day,:month,:year]%>
  -->
  <%=  form.text_field :author , :value => "#{current_user.firstname} #{current_user.lastname}" %>

  <%=  form.hidden_field :category ,:value => "news"%>
  <br/>
  <button class="btn btn-primary"><i class="icon-white icon-plus-sign"></i> Save</button>
<% end %>


    
</div>  
</div>
</div>
</div>  

app/views/news/press_release.html.erb
<div class="nosrednahabo">&nbsp;</div>
<%= session[:new_model] = @new_model %>
<%= render :partial => "shared/errors/error_messages" ,:lnew_model=>@new_model %>
<div class="row-fluid">
<div class="sbh effect8">
<div class="breadcrumb"><a href="<%= myhome_path %>">System Dashboard</a>
<i class="icon-chevron-left"></i> <a href="<%= user_news_index_path current_user %>">View My News</a> <i class="icon-chevron-left"></i> </div>
<div class="well effect7">
<div class="sbh"><h2>System Dashboard &raquo; Press Release Add </h2></div>
<div class="sbh bgff">
<div class="row-fluid">

<%= form_for current_user.news.build(:user=>current_user), :html => { :multipart => true } do |form| %>
  <%= form.label :caption %>
  <%= form.text_field :caption %>
     <%= form.hidden_field :landing_page_image, :value=>false %> 
   <%= form.label "File" %>
  <%= form.file_field :release %>
  
  <%=  form.hidden_field :category ,:value => "press_release"%>
  <br/>
  <button class="btn btn-primary"><i class="icon-white icon-plus-sign"></i> Save</button>
<% end %>


    
</div>  
</div>
</div>
</div>  

app/views/news/show.html.erb
 <div class="row-fluid">
    
   	  <div class="span12">
        <div class="sbh effect8">
       		<div class="sbhb effect7">
            <h2><%= @news.caption%></h2>
            </div>
          	<ul id="myTab" class="nav nav-tabs">
            <li class="active"><a href="#partners" data-toggle="tab"><i class="icon-globe"></i> News Story</a></li>
                   <li><a href="#" class="btn btn-success">Date : <%= time_tag @news.created_at.to_date %>.</a></li>
                   
          </ul>
          <div id="myTabContent" class="tab-content">
            <div class="tab-pane fade in active" id="partners">
				<div class="sbh fbn">
	                <%= @news.news_content.html_safe %>
                    
                </div>
                 <p class="btn btn-success">Written By: <%= @news.author %>.</p>
                  
            </div>
             
          </div>
          
          </div>

app/views/news/update.html.erb
<h1>News#update</h1>
<p>Find me in app/views/news/update.html.erb</p>